name: denbun
description: New experimental package.
version: 0.0.0
repository: https://github.com/myConsciousness/denbun
issue_tracker: https://github.com/myConsciousness/denbun/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
